OC-23597 Fixed participate form button languages
OpenClinica/enketo-oc pull request #218
Opened 2024-11-08 13:23 UTC by gushil

Closes https://jira.openclinica.com/browse/OC-23597

#### I have verified this PR works with

-   [ ] Online form submission
-   [ ] Offline form submission
-   [ ] Saving offline drafts
-   [ ] Loading offline drafts
-   [ ] Editing submissions
-   [ ] Form preview
-   [ ] None of the above

#### What else has been done to verify that this works as intended?

#### Why is this the best possible solution? Were any other approaches considered?

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

#### Do we need any specific form for testing your changes? If so, please attach one.

2024-11-13 21:05 UTC, pkolli0408 approved these changes

2024-11-13 21:06 UTC, pkolli0408 requested changes
@gushil There are some conflicts to be resolved.

2024-11-14 10:15 UTC, gushil commented
@pkolli0408 

Conflicts have been resolved.

Thanks.

2024-11-15 14:32 UTC, closed without merging

2024-11-15 14:33 UTC, gushil commented
Replaced by https://github.com/OpenClinica/enketo-oc/pull/222